#!/bin/bash
apt-get install -y build-essential
apt-get install -y ccache
apt-get install -y curl
apt-get install -y g++-multilib
apt-get install -y gcc-multilib
apt-get install -y gnupg
apt-get install -y gperf
apt-get install -y ia32-libs
apt-get install -y lib32ncurses5-dev
apt-get install -y lib32z-dev
apt-get install -y libc6-dev-i386
apt-get install -y libx11-dev
apt-get install -y mingw32
apt-get install -y openjdk-7-jdk
apt-get install -y valgrind
apt-get install -y x11proto-core-dev
apt-get install -y zip
apt-get install -y zlib1g-dev
