#!/bin/bash
apt-get install -y openssh-server
apt-get install -y ssh
apt-get install -y git-core
apt-get install -y git
apt-get install -y qgit
apt-get install -y gitg
apt-get install -y gitk
apt-get install -y tree
apt-get install -y lrzsz
apt-get install -y samba
apt-get install -y smbfs
apt-get install -y libncurses5-dev
apt-get install -y exuberant-ctags
apt-get install -y minicom
apt-get install -y flex
apt-get install -y bison
apt-get install -y apache2
apt-get install -y autoconf
apt-get install -y automake1.9
apt-get install -y vim
apt-get install -y vim-gnome
apt-get install -y patch
apt-get install -y tofrodos
apt-get install -y indent
apt-get install -y gettext
apt-get install -y meld
apt-get install -y iptux
apt-get install -y vbindiff
apt-get install -y gftp
apt-get install -y cscope
apt-get install -y mercurial
apt-get install -y subversion
apt-get install -y compizconfig-settings-manager
apt-get install -y unrar
apt-get install -y p7zip-full
apt-get install -y phatch
apt-get install -y unixodbc
apt-get install -y ruby
apt-get install -y mpg321
#to play *.ogg
apt-get install -y vorbis-tools
apt-get install -y gimp
apt-get install -y libxml2-utils
apt-get install -y graphviz
apt-get install -y policycoreutils
apt-get install -y libpq-dev
apt-get install -y ckermit
apt-get install -y phatch-cli
#add by wuyang
apt-get install -y expect
apt-get purge -y nano
